config/routes.rb
Rails.application.routes.draw do

  resources :home, only: :index
  resources :usuarios

  root :to => 'usuarios#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/usuario.rb
# encoding: UTF-8
# require 'digest'
class Usuario < ActiveRecord::Base
    self.table_name = 'usr'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    def index
    end
    
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController

    before_action :procurar_id, only: [:show, :edit, :update, :destroy]
    
    def index
        @usuarios = Usuario.all
    end

    def show
    end
    
    def new
        @usuario = Usuario.new
    end

    def create
        @usuario = Usuario.new(params.require(:usuario).permit(:nome, :senha, :conta_id, :data_de_nascimento, :login, :email, 
                               :telefone, :admin, :gerente, :empresa_id))
        if @usuario.save
                redirect_to usuarios_path
        else
            render action: 'new'
        end
    end

    def edit
    end

    def update
        if @usuario.update_attributes(params.require(:usuario).permit(:nome, :senha, :senha_confirmation, :conta_id, :data_de_nascimento, :login, :email, 
                                      :telefone, :admin, :gerente, :empresa_id))
            redirect_to usuarios_path
        else
            render 'edit'
        end
    end

    def destroy
        @usuario.destroy
        redirect_to usuarios_path
    end

    private

    def procurar_id
        @usuario = Usuario.find_by_id(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
Teste

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TesteHerokuApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/usuarios/_form.html.erb
<%= form_for @usuario, validate:true do |u| %>

    <% if @usuario.errors.any? %>
        <div class="fundo_erro">
            <h2 class="text-center">Revise as informações abaixo: </h2>
            <p> </p>
            <ul>
            <% @usuario.errors.full_messages.each do |msg| %>
            <li><%= msg.humanize %></li>
            <% end %>
            </ul>
        </div>
    <% end %>
    
    <table style="width: 100%;">
        <tbody style="width: 100%;">
            <tr>
                <td class="text-right alinhamento-label-form">
                    <%= u.label :login, class: 'text-right', style: 'width: 170px' %>
                </td>
                <td class="pb-6px">
                    <%= u.text_field :login, class: 'form-control focus-padrao', style: 'width: 100%' %>
                </td>
            </tr>
            <tr>
                <td class="text-right alinhamento-label-form">
                    <%= u.label :nome, class: 'text-right', style: 'width: 170px' %>
                </td>
                <td class="pb-6px">
                    <%= u.text_field :nome, class: 'form-control focus-padrao', style: 'width: 100%' %>
                </td>
            </tr>
            <tr>
                <td class="text-right alinhamento-label-form">
                    <%= u.label :telefone, class: 'text-right', style: 'width: 170px' %>
                </td>
                <td class="pb-6px">
                    <%= u.text_field :telefone, class: 'form-control focus-padrao phone_with_ddd', style: 'width: 100%' %>
                </td>
            </tr>
            <tr>
                <td class="text-right alinhamento-label-form">
                    <%= u.label :email, class: 'text-right', style: 'width: 170px' %>
                </td>
                <td class="pb-6px">
                    <%= u.text_field :email, class: 'form-control focus-padrao', style: 'width: 100%' %>
                </td>
            </tr>
            <tr>
                <td class="text-right alinhamento-label-form">
                    <%= u.label :senha, class: 'text-right', style: 'width: 170px' %>
                </td>
                <td class="pb-6px">
                    <%= u.password_field :senha, class: 'form-control focus-padrao', style: 'width: 100%' %>
                </td>
            </tr>
            <tr>
                <td class="text-right alinhamento-label-form">
                    <%= u.label 'Confirmação de senha', class: 'text-right', style: 'width: 170px' %>
                </td>
                <td class="pb-6px">
                    <%= u.password_field :senha_confirmation, class: 'form-control focus-padrao', style: 'width: 100%' %>
                </td>
            </tr>
            <tr>
                <td class="text-right alinhamento-label-form">
                    <%= u.label :data_de_nascimento, class: 'text-right', style: 'width: 170px' %>
                </td>
                <td class="pb-6px">
                    <%= u.date_field :data_de_nascimento, class: 'form-control focus-padrao', style: 'width: 100%;' %>
                </td>
            </tr>
                <tr>
                    <td class="text-right alinhamento-label-form">
                        <%= u.label :admin, class: 'text-right', style: 'width: 170px' %>
                    </td>
                    <td class="pb-6px pt-9px">
                        <%= u.check_box :admin, class: 'focus-check' %>
                    </td>
                </tr>
            <tr>
                <td class="text-right alinhamento-label-form">
                    <%= u.label :gerente, class: 'text-right', style: 'width: 170px' %>
                </td>
                <td class="pb-6px pt-9px">
                    <%= u.check_box :gerente, class: 'focus-check' %>
                </td>
            </tr>
        </tbody>
    </table>

    <hr class="hr-system-100por">

    <div class='width-100por text-center'>
        <%= u.submit 'Confirmar', class: 'text-center btn btn-success' %>
    </div>

<% end %>

app/views/usuarios/edit.html.erb
<div class="form-design">
    <h1 class="titulo-system">Edição do usuário: (<%= @usuario.nome %>)</h1>
    <hr class="hr-system-80por">
    <div class="width-80por">
        <%= render('form') %>
    </div>
</div>

app/views/usuarios/index.html.erb
<div class="conteudo  min-height-index-padrao-600px">
    <div class="div-cabeca-index" style="text-align: center">
        <div class="label-org-index pl-35px"> Usuários </div>
        <div class="botoes-org-index">
            <%= link_to 'Novo registro', new_usuario_path, class:'btn btn-success' %>
        </div>
    </div>
    <table class="table_index" style="<%= 'margin-top: 13px!important' unless @usuarios.blank? %>">
        <% if @usuarios.blank? %>
            <tr>
                <td colspan="2" class="nao_ha_registros">
                    Não há registros
                </td>
            </tr>
        <% else %>
            <thead>
                <tr>
                    <th class="tr_table_index text-center">ID</th>
                    <th class="tr_table_index text-center">Nome</th>
                    <th class="tr_table_index text-center">login</th>
                    <th class="tr_table_index text-center">Email</th>
                    <th class="tr_table_index text-center">Data de nascimento</th>
                    <th class="tr_table_index text-center">Telefone</th>
                    <th class="tr_table_index text-center">Admin</th>
                    <th class="tr_table_index text-center">Gerente</th>
                    <th class="tr_table_index text-center">Editar</th>
                    <th class="tr_table_index text-center">Excluir</th>
                </tr>
            </thead>
            <tbody>                
                <% @usuarios.each do |usuario| %>
                    <tr class="<%= cycle("odd", "even") -%>">
                        <td class="text-center width-60px"> <%= usuario.id %> </td>
                        <td class="width-150px"> <%= link_to usuario.nome, usuario_path(usuario), class: 'link-azul' %> </td>
                        <td class="width-150px"> <%= usuario.login %> </td>
                        <td class="width-150px"> <%= usuario.email %> </td>
                        <td class="width-150px"> <%= usuario.data_de_nascimento.strftime("%m/%d/%Y") %> </td>
                        <td class="width-150px"> <%= usuario.telefone %> </td>
                        <td class="text-center width-60px"><%= link_to('pencil', edit_usuario_path(usuario), class:'pencil') %></td>
                        <td class="text-center width-60px"><%= link_to('trash', usuario_path(usuario), method: :delete, data: { confirm: 'Deseja excluir este usuário permanentemente?' }, class: 'trash' ) %></td>
                    </tr>
                <% end %>
            </tbody>
        <% end %>
    </table>
</div>

app/views/usuarios/new.html.erb
<div class="form-design">
    <h1 class="titulo-system">Novo usuário</h1>
    <hr class="hr-system-80por">
    <div class="width-80por">
        <%= render('form') %>
    </div>
</div>

app/views/usuarios/show.html.erb
<div class="conteudo">
    <div class="div-cabeca">
        <div class="label-org"> Usuário: (<%= @usuario.nome %>) </div>
            <%= link_to 'Excluir', usuario_path(@usuario.id), data: { confirm: 'Deseja excluir este usuário permanentemente?' }, method: :delete, class:'btn btn-danger' %>
            <%= link_to 'Editar', edit_usuario_path(@usuario.id, { show: "show"}), class:'btn btn-light' %>
            <%= link_to 'Novo registro', new_usuario_path({ show: "novo", usuario: @usuario}), class:'btn btn-success' %>
    </div>
    <table class="tabela-lado-lado mt-12px">
        <tbody>
            <tr>
                <td class="td-index-esquerda"> Nome: </td>
                <td class="td-index-direita"> <%= @usuario.nome %> </td>
            </tr>
            <tr>
                <td class="td-index-esquerda"> Login: </td>
                <td class="td-index-direita"> <%= @usuario.login %> </td>
            </tr>
            <tr>
                <td class="td-index-esquerda"> Email: </td>
                <td class="td-index-direita"> <%= @usuario.email %> </td>
            </tr>
            <tr>
                <td class="td-index-esquerda"> Data de nascimento: </td>
                <td class="td-index-direita"> <%= @usuario.data_de_nascimento.strftime("%m/%d/%Y") %> </td>
            </tr>
            <tr>
                <td class="td-index-esquerda"> Telefone: </td>
                <td class="td-index-direita"> <%= @usuario.telefone %> </td>
            </tr>
        </tbody>
    </table>
</div>